version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:3000
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
    command:
      - bash
      - -c
      - echo 'Freezing container. Execute in container "yarn start"' && tail -f /dev/null

volumes:
    node_modules: null
