version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/api
    command:
      - bash
      - -c
      - echo 'Freezing container. Execute in container "python manage.py runserver 0.0.0.0:8000"' && tail -f /dev/null

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules
      - ./frontend:/app
    command:
      - bash
      - -c
      - echo 'Freezing container. Execute in container "yarn start"' && tail -f /dev/null

volumes:
    node_modules: null
