// Create a "reducer" function that determines what the new state
// should be when something happens in the app
import { createSlice } from '@reduxjs/toolkit';
import { RootState } from 'store';
import { armCPU } from 'hooks';
import { armCPU_T } from 'emulator';
import { CompilerError } from 'emulator/types';

type SliceState  = {
  cpu: armCPU_T;
  assembly: string[];
  error?: CompilerError;
};

const initialState: SliceState  = {
  cpu: armCPU,
  assembly: [],
  error: undefined,
};

export const cpuSlice = createSlice({
  name: 'cpu',
  initialState: initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setBreakpoint: (state, action) => {
      const index = action.payload / 2;
      state.cpu.program[index].break = true;
    },
    unsetBreakpoint: (state, action) => {
      const index = action.payload / 2;
      state.cpu.program[index].break = false;
    },
    setError: (state, action) => {
      state.error = action.payload;
      state.cpu.error = action.payload;
    },
    updateProgram: (state, action) => {
      state.cpu.reset();
      state.cpu.loadAssembly(action.payload);
      if (state.cpu.error) {
        state.error = state.cpu.error;
      } else {
        state.error = undefined;
      }

      action.payload = state.error;
    },
    updateRegister: (state, action) => {
      state.cpu.regs[action.payload.register] = action.payload.value;
    },
    updateMemory: (state, action) => {
      const index = action.payload.address / 4;
      state.cpu.memory[index] = action.payload.value;
    },
    runCode: (state, action) => {
      if (state.cpu.error) {
        return;
      } else {
        state.cpu.run();
      }
    },
    step: (state) => {
      state.cpu.step();
    },
    reset: (state) => {
      state.cpu.reset();
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
  },
});

export const { setBreakpoint, unsetBreakpoint, setError, updateProgram, updateRegister, updateMemory, runCode, step, reset } = cpuSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectMemory = (state: RootState) => state.cpu.cpu.memory;
export const selectProgram = (state: RootState) => state.cpu.cpu.program;
export const selectAssembly = (state: RootState) => state.cpu.assembly;

export default cpuSlice.reducer;